- name: Download (armored) GPG key
  ansible.builtin.get_url:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    dest: /tmp/crowdsec.asc

- name: Convert CrowdSec key to dearmored format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/crowdsec.gpg /tmp/crowdsec.asc
    creates: /etc/apt/keyrings/crowdsec.gpg


- name: Add CrowdSec repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/crowdsec.gpg] https://packagecloud.io/crowdsec/crowdsec/any any main"
    state: present
    filename: crowdsec

- name: Install Crowdsec
  apt:
    update_cache: true
    name: crowdsec
    state: present
  notify: restart crowdsec

# Not sure why this works better when not installed simultaneously with crowdsec
- name: Install bouncer
  apt:
    update_cache: true
    name: crowdsec-firewall-bouncer-nftables
    state: present
  notify: restart crowdsec

- name: Install custom scenarios
  copy:
    src: "{{ item }}"
    dest: /etc/crowdsec/scenarios/
  with_fileglob:
      - files/scenarios/*
  notify: restart crowdsec

# Installs badstrings.txt
- name: cscli hub upgrade
  command:
    cmd: cscli hub upgrade 
  changed_when: false

- name: Combine "users" and "additional users"
  set_fact:
    greenlist: "{{ greenlist_ips | union(additional_greenlist| default([])) }}"
  tags: crowdtest

- name: create allowlist
  command:
    cmd: "cscli allowlist create megaphone --description 'Megaphone IPs'"
  failed_when: false
  tags: crowdtest

- name: add allowlist IPs to crowdsec
  shell: "cscli allowlist add megaphone {{ greenlist|join(' ') }}"
  tags: crowdtest